//
// GetStoreAppInfoResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** iTunesStoreを検索して取得した公開中アプリの情報 */

public struct GetStoreAppInfoResponseDTO: Codable {

    /** 見つかった個数 */
    public var resultCount: Int
    public var results: [StoreAppInfo]

    public init(resultCount: Int, results: [StoreAppInfo]) {
        self.resultCount = resultCount
        self.results = results
    }

}
