//
// GetTudVersionCheckResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Json取得した公開中アプリの情報 */

public struct GetTudVersionCheckResponseDTO: Codable {

    /** チェック対象バージョン */
    public var requiredVersion: String
    /** 強制アップデートするかフラグ */
    public var type: String
    /** AppStoreへの誘導URL */
    public var updateUrl: String

    public init(requiredVersion: String, type: String, updateUrl: String) {
        self.requiredVersion = requiredVersion
        self.type = type
        self.updateUrl = updateUrl
    }
    public enum CodingKeys: String, CodingKey { 
        case requiredVersion = "required_version"
        case type
        case updateUrl = "update_url"
    }

}
