//
// GetUpdateInfoResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Json取得した公開中アプリの情報 */

public struct GetUpdateInfoResponseDTO: Codable {

    /** 必要バージョン（実行アプリが、これ未満だとダイアログが表示される） */
    public var requiredVersion: String
    /** 強制アップデートするかフラグ（trueなら〔OK〕のみ、falseなら〔OK〕〔Cancel〕でダイアログ表示される） */
    public var forceUpdate: Bool
    /** AppStore誘導ダイアログのタイトル */
    public var dialogTitle: String?
    /** AppStore誘導ダイアログのメッセージ */
    public var dialogMessage: String
    /** AppStoreへの誘導URL */
    public var updateUrl: String

    public init(requiredVersion: String, forceUpdate: Bool, dialogTitle: String?, dialogMessage: String, updateUrl: String) {
        self.requiredVersion = requiredVersion
        self.forceUpdate = forceUpdate
        self.dialogTitle = dialogTitle
        self.dialogMessage = dialogMessage
        self.updateUrl = updateUrl
    }
    public enum CodingKeys: String, CodingKey { 
        case requiredVersion = "required_version"
        case forceUpdate = "force_update"
        case dialogTitle = "dialog_title"
        case dialogMessage = "dialog_message"
        case updateUrl = "update_url"
    }

}
