# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'direct-type' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 警告非表示
  inhibit_all_warnings!

  # Pods for direct-type

  ##=== Cognito ===
  pod 'AWSMobileClient', '~> 2.13.0'      # Required dependency

  ##=== PromiseKit
#  pod "PromiseKit", "~> 6.8"

  ##=== Swagger ===（仮定義なアプリモデル生成用）
  pod 'SwaggerClient', :path => '../generated/promise'

  ##=== Swagger ===（シルバーエッグレコメンド叩くIF）
  pod 'SERecommend', :path => '../generatedRecommend/promise'
  
  ##=== Swagger ===（最終的なサーバ側API）
  pod 'TudApi', :path => '../generatedSvr/promise'
  
  ##=== Progress
  pod 'SVProgressHUD'
  
  ##=== Image
  pod 'AlamofireImage'
  
  ##=== Graph
  pod 'Charts'
  pod 'MBCircularProgressBar'

  ##=== Projects
  pod 'R.swift'

end

#post_install do | installer |
#  require 'fileutils'
#  FileUtils.cp_r('Pods/Target Support Files/Pods-direct-type/Pods-direct-type-#acknowledgements.plist', 'direct-type/Settings.bundle/#Acknowledgements.plist', :remove_destination => true)

#end
