//
// TudUpdateInfoAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import PromiseKit



open class TudUpdateInfoAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func appInfoDirecttypeNetDirectTypeIosVersionJsonGet(completion: @escaping ((_ data: GetUpdateInfoResponseDTO?,_ error: Error?) -> Void)) {
        appInfoDirecttypeNetDirectTypeIosVersionJsonGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**

     - returns: Promise<GetUpdateInfoResponseDTO>
     */
    open class func appInfoDirecttypeNetDirectTypeIosVersionJsonGet() -> Promise<GetUpdateInfoResponseDTO> {
        //let deferred = Promise<GetUpdateInfoResponseDTO>.pending()
        let (promise, resolver) = Promise<GetUpdateInfoResponseDTO>.pending()
        appInfoDirecttypeNetDirectTypeIosVersionJsonGet() { data, error in
            if let error = error {
                //deferred.reject(error)
                resolver.reject(error)
            } else {
                //deferred.fulfill(data!)
                resolver.fulfill(data!)
            }
        }
        //return deferred.promise
        return promise
    }

    /**
     - GET /app-info.directtype.net/direct-type-ios-version.json
     - TudVersionCheck用のJSONを取得する 
     - examples: [{contentType=application/json, example={
  "required_version" : "required_version",
  "dialog_message" : "dialog_message",
  "dialog_title" : "dialog_title",
  "update_url" : "update_url",
  "force_update" : true
}}]

     - returns: RequestBuilder<GetUpdateInfoResponseDTO> 
     */
    open class func appInfoDirecttypeNetDirectTypeIosVersionJsonGetWithRequestBuilder() -> RequestBuilder<GetUpdateInfoResponseDTO> {
        let path = "/app-info.directtype.net/direct-type-ios-version.json"
        let URLString = TudVerCheckAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<GetUpdateInfoResponseDTO>.Type = TudVerCheckAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
